- repo: git://github.com/diogoaurelio/pre-commit-terraform
  sha: v1.5.0
  hooks:
    - id: terraform_fmt
- repo: git://github.com/joaoferrao/pre-commit-terraform-vars
  sha: master
  hooks:
    - id: terraform-vars
